// angular-client/src/app/book-list/book-list.component.ts
import { Component, OnInit } from '@angular/core';
import {Book} from "../book";
import {BookService} from "../book.service";
import {HttpErrorResponse} from "@angular/common/http";
import {Router} from "@angular/router";


@Component({
  selector: 'app-book-list',
  templateUrl: './book-list.component.html',
  styleUrls: ['./book-list.component.css']
})
export class BookListComponent implements OnInit {
  public books: Book[] = [];

  constructor(private bookService: BookService,
              private router:Router) {
  }

  ngOnInit(): void {
    console.log("booklist")
    this.getBooks();
  }

  public getBooks(): void {
    this.bookService.findAllBooks().subscribe(
      (response: Book[]) => {
        this.books = response;
      },
      (error: HttpErrorResponse) => {
        alert(error.message);
      }
    );
  }
  public deleteBook(id:number){
    this.bookService.deleteBook(id).subscribe( data => {
      this.getBooks();
    })
  }
  public editBook(id:number){
    this.router.navigate(['edit-book',{id:id}]);
  }


  }

<h1 class="text-center" style="padding-top: 30px"> Библиотека </h1>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col">Имя книги</th>
        <th scope="col">Жанр</th>
        <th scope="col">Авторы</th>
        <th scope="col">Действия</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let book of books">
        <td>{{ book.name }}</td>
        <td>{{book.genre.name}}</td>
        <td><p *ngFor="let author of book.authors">{{author.name}}</p></td>
        <td>

          <button class="book-btn btn btn-danger" style="background: green; border-color: green"(click)="editBook(book.id)"> Изменить</button>
          <br>
          <button class="book-btn btn btn-danger" (click)="deleteBook(book.id)"> Удалить</button>
        </td>
      </tr>

      </tbody>
    </table>
  </div>

// react-client/src/components/BookListComponent.js

import {useEffect, useState} from "react";
import BookService from "../services/BookService";
import {Link} from "react-router-dom";
import bookService from "../services/BookService";
import FilterComponent from "./FilterComponent";

const BookListComponent = ()=>{
    const title="Библиотека"
    const [books,setBooks]=useState([]);
    const [savebooks,setSaveBooks]=useState([]);
    const [status,setStatus]=useState('')


    useEffect(()=>{
        setStatus("Загрузка...")
        getBooks()
        console.log(books)
    },[])

   const getBooks=()=>{
        BookService.getBooks().then(
            (res) => {
                setBooks(res.data)
                setSaveBooks(res.data)
                setStatus("Пусто")
            }).catch(error =>{
            console.log(error);
        })
    }

    const reloadBooks=()=>{
       setBooks(savebooks)
    }

   const deleteBook=(id)=>{
        bookService.deleteBook(id).then(()=>{
            getBooks()
        }).catch(error =>{
            console.log(error);
        })
    }

    const returnedValue=(genre,author)=>{
     setBooks(books.filter(book=>
         book.genre.name.includes(genre) &&
         (book.authors.filter(auth =>
                 auth.name.toLowerCase().includes(author.toLowerCase())).length >= 1
         )
     ))
    }

        return (
            <div>
                <h1 className="text-center" style={{paddingTop: 30}}> {title}</h1>
                <div className="grid" style={{rowGap:10}}>
                    <div className="row gx-5">
                        <div className=" col-lg-9" >
                            <div className="card">
                    <div className="card-body" >
                        <table className="table table-bordered table-striped " style={{textAlign:"left"}}>
                            <thead className="thead-dark bg-info">
                            <tr className="text-center col-auto">
                                <th scope="col" >Имя книги</th>
                                <th scope="col">Жанр</th>
                                <th scope="col">Авторы</th>
                                <th scope="col" >Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            {
                                books.length!==0?
                                books.map(
                                    book =>
                                        <tr >
                                            <td>{book.name}</td>
                                            <td>{book.genre.name}</td>
                                            <td>
                                                {
                                                    book.authors.map(
                                                        author =>
                                                            <p key={author.id}>{author.name}</p>
                                                    )
                                                }
                                            </td>
                                            <td >
                                                <Link to={`/edit-book/${book.id}`} className="btn btn-secondary " style={{margin:2}} >Изменить</Link>
                                                <br/>
                                                <button className="btn btn-danger"  style={{margin:2}} onClick={()=>deleteBook(book.id)}>Удалить</button>
                                            </td>
                                        </tr>
                                ):
                                    <tr>
                                        <td className="text-center" colSpan="4">
                                            {status}
                                        </td>
                                    </tr>
                            }
                            </tbody>
                        </table>
                        <div className="row-cols-auto" style={{ textAlign: "right",}}>
                            <Link to="/add-book" className="btn btn-primary" >Добавить книгу</Link>
                        </div>
                    </div>
                            </div>
                </div>
                        <div className=" my-5 col-3" >
                                <FilterComponent reload={reloadBooks} returnValue={returnedValue} />
                        </div>
                    </div>
                </div>
            </div>
        )

}
export default  BookListComponent;
